# Generated by Django 5.2.4 on 2025-07-26 18:05

from django.db import migrations, models

def create_single_digit_addition_problems(apps, schema_editor):
    Problem = apps.get_model('problems', 'Problem')
    for i in range(10):
        for j in range(10):
            problem = Problem(question=f'{i} + {j}', answer = i + j, type="Single-digit addition")
            problem.save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.RunPython(create_single_digit_addition_problems),
    ]
