# Generated by Django 5.2.4 on 2025-07-26 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='problem',
            new_name='question',
        ),
    ]
